### ISSUE TITLE
Regarding result when h,g,p = 45,2,89

### ISSUE THREAD

**Issue by prsm2017** [mcerovic/pohlig-hellman#1]
Hi
Thx for the nice program. 

This seems to give 32 for  h=45, g= 2 and p=89.  
Should it rather give 10 (because 2^10 = 1024 === 45 (mod 89))?

TIA for your time!
prsm

**Comment by mcerovic** [comment]
Hi,

If I remember correctly g needs to be a generator of the group G = {0, 1, ... p - 1}

I wrote a simple script that should check if a number is generator of a group with order p - 1.

p = 89
g = 2
x = map(int, [(g ** i % p) for i in range(p - 1)])
y = [(i + 1) for i in range(p - 1)]
set(x) == set(y) # True if g is generator, False otherwise

In this case it will be False..

Check out this document http://www-math.ucdenver.edu/~wcherowi/courses/m5410/phexam.html

For their example g = 6, p = 8101 the result will be True.

Best regards,
mcerovic
